### ISSUE TITLE
Error After Composer Update

### ISSUE THREAD

**Issue by fhariano** [llvdl/Slim-Translations-Example#4]
Hi, I am getting an error after composer update  (because I have that use the version latest of SLIM):

Details
Type: TypeError
Message: Argument 1 passed to App\Middleware\LocaleMiddleware::__construct() must be an instance of Symfony\Component\Translation\TranslatorInterface, instance of Illuminate\Translation\Translator given, called in C:\inetpub\wwwroot\Slim-Translations\app\config\dependencies\middleware.php on line 13
File: C:\inetpub\wwwroot\Slim-Translations\src\Middleware\LocaleMiddleware.php
Line: 32

**Comment by llvdl** [comment]
Thanks for submitting this issue. 

Apparantly the interface of the Laravel Translator class has been changed. I have updated the dependencies and modified the code to make use of the new Translator interface.

**Comment by fhariano** [comment]
It's great now!

Thank you very much.
